2025-07-15 12:25:33 - INFO - Iniciando aplicación - Probando sistema de logging
2025-07-15 12:25:33 - DEBUG - Este es un mensaje de debug (solo en archivo)
2025-07-15 12:25:33 - INFO - Este es un mensaje de info (consola y archivo)
2025-07-15 12:25:33 - WARNING - Este es un mensaje de warning (consola, archivo y Telegram)
2025-07-15 12:25:33 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:25:33 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 337
2025-07-15 12:25:33 - ERROR -  Este es un mensaje de error (consola, archivo y Telegram)
2025-07-15 12:25:33 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:25:34 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 334
2025-07-15 12:25:34 - CRITICAL -  Este es un mensaje crítico (consola, archivo y Telegram)
2025-07-15 12:25:34 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:25:35 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 341
2025-07-15 12:25:35 - ERROR -  Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 88, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 12:25:35 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:25:35 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 12:25:35 - INFO -  Pruebas de logging completadas
2025-07-15 12:34:59 - WARNING - ¡Prueba de Telegram!
2025-07-15 12:34:59 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:35:00 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 442
2025-07-15 12:38:31 - INFO - Iniciando aplicación...
2025-07-15 12:38:31 - WARNING - ¡Prueba de Telegram!
2025-07-15 12:38:31 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:38:31 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 442
2025-07-15 12:38:31 - ERROR - Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 72, in <module>
    1/0  # Forzar error
    ~^~
ZeroDivisionError: division by zero
2025-07-15 12:38:31 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:38:32 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 12:38:32 - INFO - Pruebas completadas
2025-07-15 12:55:52 | telegram_logger.py:103 | <module> | DEBUG | Mensaje de debug (solo en archivo)
2025-07-15 12:55:52 | telegram_logger.py:104 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 12:55:52 | telegram_logger.py:105 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 12:55:52 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:55:53 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 12:55:53 | telegram_logger.py:111 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 109, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 12:55:53 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:55:53 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 12:55:53 | telegram_logger.py:113 | <module> | INFO | Pruebas completadas
2025-07-15 12:56:44 | telegram_logger.py:103 | <module> | DEBUG | Mensaje de debug (solo en archivo)
2025-07-15 12:56:44 | telegram_logger.py:104 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 12:56:44 | telegram_logger.py:105 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 12:56:44 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:56:44 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 12:56:44 | telegram_logger.py:111 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 109, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 12:56:44 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 12:56:45 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 12:56:45 | telegram_logger.py:113 | <module> | INFO | Pruebas completadas
2025-07-15 13:01:16 | telegram_logger.py:103 | <module> | DEBUG | Mensaje de debug (solo en archivo)
2025-07-15 13:01:16 | telegram_logger.py:104 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 13:01:16 | telegram_logger.py:105 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 13:01:16 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:01:17 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:01:17 | telegram_logger.py:111 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 109, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:01:17 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:01:17 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:01:17 | telegram_logger.py:113 | <module> | INFO | Pruebas completadas
2025-07-15 13:05:14 | telegram_logger.py:108 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 13:05:14 | telegram_logger.py:109 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 13:05:14 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:05:14 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:05:14 | telegram_logger.py:115 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 113, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:05:14 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:05:15 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:05:15 | telegram_logger.py:117 | <module> | INFO | Pruebas completadas
2025-07-15 13:07:28 - INFO - Iniciando aplicación...
2025-07-15 13:07:28 - WARNING - ¡Prueba de Telegram!
2025-07-15 13:07:28 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:07:29 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 154
2025-07-15 13:07:29 - ERROR - Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 72, in <module>
    1/0  # Forzar error
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:07:29 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:07:29 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 13:07:29 - INFO - Pruebas completadas
2025-07-15 13:08:08 - INFO - Iniciando aplicación...
2025-07-15 13:08:08 - WARNING - ¡Prueba de Telegram!
2025-07-15 13:08:08 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:08:09 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 284
2025-07-15 13:08:09 - ERROR - Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 72, in <module>
    1/0  # Forzar error
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:08:09 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:08:09 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 13:08:09 - INFO - Pruebas completadas
2025-07-15 13:08:31 | telegram_logger.py:108 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 13:08:31 | telegram_logger.py:109 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 13:08:31 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:08:32 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:08:32 | telegram_logger.py:115 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 113, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:08:32 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:08:33 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 131
2025-07-15 13:08:33 | telegram_logger.py:117 | <module> | INFO | Pruebas completadas
2025-07-15 13:17:03 | telegram_logger.py:112 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 13:17:03 | telegram_logger.py:113 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 13:17:03 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:17:03 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot%207782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 404 55
2025-07-15 13:17:03 | telegram_logger.py:119 | <module> | ERROR | Error al dividir: division by zero
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 117, in <module>
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
2025-07-15 13:17:03 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:17:04 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot%207782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 404 55
2025-07-15 13:17:04 | telegram_logger.py:121 | <module> | INFO | Pruebas completadas
2025-07-15 13:28:44 - INFO - Iniciando aplicación...
2025-07-15 13:28:44 - WARNING - ¡Prueba de Telegram!
2025-07-15 13:28:44 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:28:44 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 154
2025-07-15 13:28:44 - ERROR - Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 72, in <module>
    1/0  # Forzar error
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:28:44 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:28:45 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 13:28:45 - INFO - Pruebas completadas
2025-07-15 13:29:32 - INFO - Iniciando aplicación...
2025-07-15 13:29:32 - WARNING - ¡Prueba de Telegram!
2025-07-15 13:29:32 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:29:32 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 200 284
2025-07-15 13:29:32 - ERROR - Ocurrió una excepción
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela Politécnica Nacional\Documentos\4to Semestre\MétodosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 72, in <module>
    1/0  # Forzar error
    ~^~
ZeroDivisionError: division by zero
2025-07-15 13:29:32 - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:29:33 - DEBUG - https://api.telegram.org:443 "POST /bot7782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 400 132
2025-07-15 13:29:33 - INFO - Pruebas completadas
2025-07-15 13:32:00 | telegram_logger.py:97 | <module> | INFO | Iniciando aplicaciÃ³n...
2025-07-15 13:32:00 | telegram_logger.py:98 | <module> | WARNING | Â¡Prueba de Telegram!
2025-07-15 13:32:00 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:32:00 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot%207782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 404 55
2025-07-15 13:32:00 | telegram_logger.py:103 | <module> | ERROR | OcurriÃ³ una excepciÃ³n
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive - Escuela PolitÃ©cnica Nacional\Documentos\4to Semestre\MÃ©todosNumericos\DeberesMetodos\DeberesExtracurriculares\Logging\telegram_logger.py", line 101, in <module>
    1 / 0  # Forzar error
    ~~^~~
ZeroDivisionError: division by zero
2025-07-15 13:32:00 | connectionpool.py:1049 | _new_conn | DEBUG | Starting new HTTPS connection (1): api.telegram.org:443
2025-07-15 13:32:01 | connectionpool.py:544 | _make_request | DEBUG | https://api.telegram.org:443 "POST /bot%207782114763:AAG95EeBfC6Wd7rSEa88cidvMCTX9lkBQUE/sendMessage HTTP/1.1" 404 55
2025-07-15 13:32:01 | telegram_logger.py:105 | <module> | INFO | Pruebas completadas
